apiVersion: v1
kind: Service
metadata:
  name: spring-crud-kubernetes-service
spec:
  selector:
    app: spring-crud-kubernetes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-crud-kubernetes
spec:
  selector:
    matchLabels:
      app: spring-crud-kubernetes
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-crud-kubernetes
    spec:
      containers:
        - name: spring-crud-kubernetes
          image: spring-crud-mysql-kubernetes-i:1.1
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: name
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials # Secret Name
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
